In [1]:
import numpy as np

zer = np.zeros((2,5))
print(zer)
print(zer + 5)
print(zer.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
(2, 5)


In [2]:
matrix = np.random.random((3,3))
print(matrix)
matrix.sort()
print(matrix)

[[0.37343801 0.30126158 0.33860674]
 [0.75203056 0.50727198 0.16504571]
 [0.54160177 0.60334365 0.60673304]]
[[0.30126158 0.33860674 0.37343801]
 [0.16504571 0.50727198 0.75203056]
 [0.54160177 0.60334365 0.60673304]]


In [3]:
print(np.random.randint(1, 5, (3,4)))

[[4 2 1 1]
 [2 3 3 3]
 [1 4 2 4]]


In [4]:
x = np.linspace(0,4,10)
print(x)

[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [5]:
print(x.mean(), x.sum(), x.max())

2.0 20.0 4.0


In [6]:
x2 = np.reshape(x, (5, 2))
print(x2)
print(x2.shape)
print(x2.mean())
print(x2.sum())

[[0.         0.44444444]
 [0.88888889 1.33333333]
 [1.77777778 2.22222222]
 [2.66666667 3.11111111]
 [3.55555556 4.        ]]
(5, 2)
2.0
20.0


In [7]:
y = np.linspace(0,4,10).reshape(-1,1)
print(y)

[[0.        ]
 [0.44444444]
 [0.88888889]
 [1.33333333]
 [1.77777778]
 [2.22222222]
 [2.66666667]
 [3.11111111]
 [3.55555556]
 [4.        ]]


In [8]:
print(x @ y) # np.dot(x,y)
print((y**2).sum())

[56.2962963]
56.29629629629629


In [9]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[3 5 9 0 4 6 1 7 2 8]


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 0 6]]


In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.copy()[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [ ]:
x = np.random.random((2,4))
print(x)
print(x.T)

[[0.69515204 0.54205252 0.41990039 0.54295413]
 [0.82804678 0.20929654 0.74152849 0.70543345]]
[[0.69515204 0.82804678]
 [0.54205252 0.20929654]
 [0.41990039 0.74152849]
 [0.54295413 0.70543345]]
